services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - airflow-network
    mem_limit: 10240m

  airflow:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API__JWT_SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API_AUTH__JWT_SECRET="another-random-base64-string"
      - AIRFLOW__API__JWT_ALGORITHM=HS512
      - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API__SECRET_KEY=Xb3f9KjMf7q2L1sTgHcR4w==
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__BASE_URL=http://airflow:8080
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - AIRFLOW__API__WORKERS=2
      - AIRFLOW__API__WORKER_REFRESH_INTERVAL=300
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - .:/app
    ports:
      - "8080:8080"
    command: airflow api-server
    restart: always
    networks:
      - airflow-network
    mem_limit: 10240m

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    depends_on:
      - postgres
      - airflow
    environment:
      - PYTHONPATH=/app
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API__SECRET_KEY=Xb3f9KjMf7q2L1sTgHcR4w==
      - AIRFLOW__API_AUTH__JWT_SECRET="another-random-base64-string"
      - AIRFLOW__API__JWT_SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API__JWT_ALGORITHM=HS512
      - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__API__BASE_URL=http://airflow:8080
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - .:/app
    command: airflow scheduler
    restart: always
    networks:
      - airflow-network
    mem_limit: 10240m

networks:
  airflow-network:
    driver: bridge

volumes:
  postgres-db-volume:
